### ISSUE TITLE
Refactor with hooks

### ISSUE THREAD

**Issue by ram1117** [ram1117/math-magicians#4]
Hi, I used functional components as per the project requirements .I used useState hook in my project to update values displayed in my calculator display, when I added event listeners in the previous milestone. 

https://github.com/ram1117/math-magicians/blob/3b582642f7703a76391b1eeb0f371c4b7a7f8cf0/src/components/Calculator.js#L5-L9

I am able to perform calculations on the calculator.

![Peek 2023-02-15 13-44](https://user-images.githubusercontent.com/116718155/219038712-c7f115c2-7a84-4d21-a2df-7e0f700d4186.gif)

The project requirement for `Refactor with hooks` milestone has been updated recently. PFA screenshot 

![image](https://user-images.githubusercontent.com/116718155/219038436-4b36ff71-d99a-4f47-8f46-17a0c86ee5b2.png)

Please approve my project for `Refactor with hooks` milestone.

**Comment by youmari** [comment]
# Project Approved :trophy: :tada: 🟢 

Hi @ram1117 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
